makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
remote_theme: pages-themes/minimal@v0.2.0
title: 'Aprendiendo Microbit'
description: 'Mis primeros pasos con Microbit MB'
asignatura: 'Aprendizaje y Enseñanza de la Tecnología'
lista:
  - uno
  - dos
  - tres
plugins:
  - jekyll-remote-theme
include:
  - assets
  - README.md
